sudo: required
services:
    - docker

before_install:
    - docker build -t luisfguzman/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true luisfguzman/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-047909440977"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:
        secure: "$AWS_ACCESS_KEY_ID"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"